title: Project

columns:
  - width: 1/2
      sections:
        info:
          type: fields
          fields:
            category:
              type: select
              options: 
                - Product Design
                - Editorial
                - Graphic Design
                - Photography
              width: 1/2
            year:
              before: Finished
              type: number
              width: 1/2
              min: 2010
            client: 
              type: text
              width: 1/2
              icon: user
            link:
              type: url
              width: 1/2
            text:
              label: Project description
              type: textarea
              help: See our content styleguide
              required: true
            tag:
              type: tags
            location:
              type: locator
              

  - width: 1/2
      sections:
        gallery:
          headline: Project gallery
          size: tiny
          info: "{{ file.dimensions }}"
          type: files
          min: 1
          max: 20
          layout: cards
          template: gallery-image
          image:
            ratio: 1/1
            cover: true
